function [ phi ] = rPIEupdate_blockstoch_2DTPA_SCPMprobes( psi,          ...
                                                           phi,          ...
                                                           T,            ...
                                                           vs_r,         ...
                                                           vs_c,         ...
                                                           rs,           ...
                                                           update_order, ...
                                                           rPIE_alpha,   ...
                                                           shifttype )
                                      
% rPIEupdate_blockstoch_2DTPA_SCPMprobes                          

max_abs_sample_abs2 = max( abs( T( : )) .^ 2 );

for ss = update_order     % order * DOES * matter here !!!

    TFview = getview_2DsampleTF( T, vs_r, vs_c, rs( ss, : ), shifttype );
    
    % ePIE
    phi = phi + conj( TFview ) .* ( psi( :, :, :, ss ) - phi .* TFview ) / max_abs_sample_abs2;
    
%     % rPIE
%     phi = phi + conj( TFview ) .* ( psi( :, :, :, ss ) - phi .* TFview ) ./ ( rPIE_alpha * max_abs_sample_abs2 + ( 1 - rPIE_alpha ) * abs( TFview ) .^ 2 );
   
end
