function [ phi ] = rPIEupdate_blockstoch_2DTPA_SCPMprobes( psi,          ...
                                                           phi,          ...
                                                           T,            ...
                                                           vs_r,         ...
                                                           vs_c,         ...
                                                           rs,           ...
                                                           update_order, ...
                                                           rPIE_alpha,   ...
                                                           shifttype )
                                      
%========================================
% update order ***DOES*** matter here !!!
%========================================

for ss = update_order                   

    TFview = getview_2DsampleTF( T, vs_r, vs_c, rs( ss, : ), shifttype );
    
    abs2_sample = abs( TFview ) .^ 2;
    max_abs2_sample = max( abs2_sample( : ));

    phi = phi + conj( TFview ) .* ( psi( :, :, :, ss ) - phi .* TFview ) ./ ( rPIE_alpha * max_abs2_sample + ( 1 - rPIE_alpha ) * abs2_sample );
   
end
